did.go
document.go
document_test.go

What has changed:
* Easy adding of VerificationMethods as Authentication
* Prevent duplicate verificationMethods
* When adding, if the controller on a verificationMethod is not set, set it to the document ID.

Add AddAuthentication method

---

vc.go

`ExpirationDate` and `CredentialStatus` are optional in the VC JSON output.

omit optional VC fields

---

vc/json.go
vc/vc.go
vc/vc_test.go

See https://www.w3.org/TR/vc-data-model/#types
Found while testing `nuts-node` when issuing VCs, because its API states it requires the type as string, but when passed it's unmarshaled as VC which requires it to be a slice. The spec however states both are supported.

Support VC types with a single value

---

README.md
did/did.go
did/did_test.go
did/document_test.go
did/validator.go
did/validator_test.go
go.mod
go.sum

Fixes #38 
Note: This change breaks all calls to ParseDID() which are verificationMethods and services IDs

Support DIDURLs and stricter DID parsing

---

did/did.go
did/did_test.go

This way `errors.Is(err, ErrInvalidDID)` can be used.

Provide callers of ParseDID with assertable error

---

did/did.go
did/did_test.go
go.sum
types.go
types_test.go

Go's YAML marshaler uses `encoding.TextMarshaler` to allow for hooking up "custom" marshaling. DIDs and URIs are now marshaled (to YAML) very ugly:
```
did:
method: ""
id: ""
idstrings: []
params: []
path: ""
pathsegments: []
query: ""
fragment: ""
```
Implementing the interface fixes this.

Let scalar types implement encoding.TextMarshaler to aid YAML encoding

---

did/document.go
did/document_test.go

closes #63
removing a verificationMethod on the document ensures removal from verificationRelations as well.

Move VerificationMethods.Remove to DID Document

---

.github/workflows/go-test.yaml

CircleCI build is failing. Good time to move to a github actions build.

replace circleci with github actions

---

vc/proof.go

according to https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json `challenge` is a property of JsonWebSignature2020. It's not contained by Proof.

add challenge to JsonWebSignature2020

---

vc/proof.go

newly added challenge must be optional or old proofs are invalid

---

did/did.go
did/did_test.go
go.mod
go.sum

Replaced with simple URL parsing.
If we want to support did:web we either need to update the library to support percent-encoded DID IDs, or replace it. Seeing the library, I figured replacing is in the long run more easier; one less dependency and less complicated code.

Remove unmaintained ockam/did library, can't support did:web

---

did/did.go
did/did_test.go

Given the following comment:
> This implementation does not support path escape, and it does not preserve nor compare empty fragments and queries correctly.
This PR adds support for comparing `nil` query vs an empty map. It also adds ID, Path and Fragment in their decoded forms.
Empty fragments are already compared correctly, since for `did:example:123#` the fragment is an empty string. I don't think we need to preserve empty fragments and queries when parsing and then marshalling again: while an empty fragment or query differs syntactically, it does not have semantic value i.m.o.

Equal() handles empty query, provide decoded parts

---

did/document.go
did/document_test.go
did/test/did1-expected.json
did/test/did1.json

Specified by https://www.w3.org/TR/did-core/#also-known-as
We probably want to for out derived did:web documents, referring to did:nuts.

Add alsoKnownAs property to DID document

---

vc/vc.go
vc/vc_test.go

Unmarshalling (non-normative) example of JWT-VC presentation profile breaks (https://identity.foundation/jwt-vc-presentation-profile/#vc-jwt). It should be a URI (https://www.w3.org/TR/vc-data-model/#status).

credentialStatus.id must be a URI, not URL

---

did/document.go
did/document_test.go
go.mod
go.sum

Adds support for verification method's `publicKeyMultibase` property, which replaced `publicKeyMultibase58` in de DID core data model. Changes:
- `NewVerificationMethod` for Edwards key types now fill the multibase property, not base58
- Added `publicKeyMultibase` (also supported by `PublicKey()`)
- Unmarshalling now validates that only 1 of `publicKeyJwk`, `publicKeyBase58` or `publicKeyMultibase` is set

Add support for publicKeyMultibase, deprecate publicKeyBase58

---

README.md
did/document.go
did/document_test.go
vc/vc.go
vc/vc_test.go
vc/vp.go
vc/vp_test.go

Required for supporting it in the Nuts node; we can now use the same struct for representing in either JSON-LD or JWT format. I moved most of the `UnmarshalJSON` code to the `Parse` functions (which it now calls), to accomodate parsing VCs and VPs outside of JSON documents.
Specification: https://www.w3.org/TR/vc-data-model/#json-web-token
Includes https://github.com/nuts-foundation/go-did/pull/84
TODO:

Support VCs and VPs in JWT format

---

internal/marshal/marshal.go
vc/vc.go
vc/vc_test.go
vc/vp.go
vc/vp_test.go

When integrating in Nuts node, I came across a few bugs:
- Typo in `JWTCredentialsProofFormat` const name
- `MarshalJSON()` for Verifiable Credentials in JWT format returned the VC as JSON (as if it were JSON-LD), instead of the parsed JWT VC
- JWT VCs contained null/empty values for properties that are specified as JWT claims (`issuanceDate`, `issuer`, `proof`). Moved JWT creation function from Nuts node to this library to create JWT credential without setting null/empty properties.
- Made `expirationDate` in Verifiable Credential in JWT format optional (now led to a zero-ed `time.Time`)

Bugfixes for integration

---

README.md

the config.yaml has been removed, so this always fails
probably also need to stop building the repo on https://circleci.com/gh/nuts-foundation/go-did

Remove CircleCI badge from readme

---

did/document.go
did/document_test.go
did/validator.go
did/validator_test.go

For JSON-LD documents, `@context` can contain a graph (object).

Support JSON-LD graph in document @context

---

did/did.go
did/did_test.go
did/didurl.go
did/didurl_test.go
did/document.go
did/document_test.go
did/validator.go
did/validator_test.go

Implements https://www.w3.org/TR/did-core/#relative-did-urls
Verification method IDs can be relative to their document DID. The same applies to relationships.
It also applies to service IDs, but those are URIs (rather than DID URLs), so those already parsed correctly (and we don't do any resolving on the IDs in this library).
Required for supporting SIOPv2/OpenID4VP flow with Microsoft Authenticator

Support relative DID URLs for verification method IDs

---

vc/json.go
vc/vc.go
vc/vc_test.go

Needed to introduce StatusList2021 ~I can't find in the spec if `credentialStatus` can be an array or not. All examples are objects.~ CredentialStatus can be an array or an object so applied similar logic as the other plural fields.
Marshaling of the `credentialStatus` is slightly different from the `credentialSubject` and `proof` fields since its format is not necessarily defined by the credential type. A credential type could require using one of several CredentialStatus mechanisms.

Add UnmarshalCredentialStatus

---

README.md
did/document.go
did/json.go
did/test/did1-expected.json
internal/marshal/marshal.go
vc/vc.go
vc/vc_test.go
vc/vp.go
vc/vp_test.go

This makes it hard to predict what the marshalled JSON object will look like, meaning things like creating presentation submissions will be harder. E.g., input descriptor mapping path can be indexed or not, depending on the number of VCs in the VP.
We also incorrectly applied the principal to serviceEndpoint, fixed that as well.
We should still support parsing compacted arrays, of course.

Don't compact arrays

---

did/did.go
did/did_test.go

Found when using a `did:web` with port

Do not double-escape when converting a DID to URI

---

vc/vc.go
vc/vc_test.go

These were added as they are in the statuslist2021 spec, but that spec is already aligned with the vc-data-model v2. We are using v1 credentials and should use issuanceDate and expirationDate

Revert validFrom and validUntil

---

did/document.go
did/document_test.go
spec-registries.go

Adds New Verification Method for ED25519VerificationKey2020, adds supporting testcase

Adds New VerificationMethod ED25519VerificationKey2020

---

vc/vc.go
vc/vc_test.go

to prevent `"proof": null` in [holder claims](https://www.w3.org/TR/vc-data-model-2.0/#presentations-including-holder-claims)

Add omitempty to vc.Proof tag
